Description: This is the Stack Description
Resources:
  lambdaRoleC844FDB1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Lambda role for ts-lambda
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/ReadOnlyAccess
      RoleName: ts-lambda-lambda-role-develop
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/lambdaRole/Resource
  lambdaExecutionAccess82ECF6E2:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: lambdaExecutionAccess
      Roles:
        - Ref: lambdaRoleC844FDB1
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/lambdaExecutionAccess/Resource
  lambdaLayer857D4AF4:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      Content:
        S3Bucket: cdk-hnb659fds-assets-043309344022-us-east-1
        S3Key: 18321b194c49336cd06457c19e68237a846320af1aaf25f56f49454dd8ba163b.zip
      Description: Lambda Layer for ts-lambda
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/lambdaLayer/Resource
      aws:asset:path: C:\Users\RanvirsinhPatil\Desktop\Nodejs\aws-lambda-challenge\packages\infrastructure\lambda-layer
      aws:asset:is-bundled: false
      aws:asset:property: Content
  hellofunctionDB70DA8B:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-043309344022-us-east-1
        S3Key: 5b55821ce2f670d9ebe6fce76f4b0359760082a7cb39f41b0b66ab7d3d9f1554.zip
      FunctionName: ts-lambda-hello-function-develop
      Handler: index.handler
      Layers:
        - Ref: lambdaLayer857D4AF4
      MemorySize: 1024
      Role:
        Fn::GetAtt:
          - lambdaRoleC844FDB1
          - Arn
      Runtime: nodejs18.x
      Timeout: 600
    DependsOn:
      - lambdaRoleC844FDB1
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/hello-function/Resource
      aws:asset:path: C:\Users\RanvirsinhPatil\Desktop\Nodejs\aws-lambda-challenge\packages\infrastructure\cdk.out\asset.5b55821ce2f670d9ebe6fce76f4b0359760082a7cb39f41b0b66ab7d3d9f1554
      aws:asset:is-bundled: true
      aws:asset:property: Code
  fnhellofunctionloggroupFB71EB37:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ts-lambda-hello-function-develop
      RetentionInDays: 30
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/fn-hello-function-log-group/Resource
  HelloApi3F989F66:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Hello API
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Resource
  HelloApiDeployment955828089827222ec27ac36389fc5b44a1b994b3:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: HelloApi3F989F66
    DependsOn:
      - HelloApidocsGETFEB011E8
      - HelloApidocs57AB0EEC
      - HelloApihelloGET34B3ECE0
      - HelloApihello0292B1E3
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Deployment/Resource
  HelloApiDeploymentStagedev13C3ED9E:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: HelloApiDeployment955828089827222ec27ac36389fc5b44a1b994b3
      RestApiId:
        Ref: HelloApi3F989F66
      StageName: dev
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/DeploymentStage.dev/Resource
  HelloApihello0292B1E3:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - HelloApi3F989F66
          - RootResourceId
      PathPart: hello
      RestApiId:
        Ref: HelloApi3F989F66
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/hello/Resource
  HelloApihelloGETApiPermissiontslambdastackdevelopHelloApiC69CBCB1GEThelloF881D042:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - hellofunctionDB70DA8B
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:043309344022:"
            - Ref: HelloApi3F989F66
            - /
            - Ref: HelloApiDeploymentStagedev13C3ED9E
            - /GET/hello
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/hello/GET/ApiPermission.tslambdastackdevelopHelloApiC69CBCB1.GET..hello
  HelloApihelloGETApiPermissionTesttslambdastackdevelopHelloApiC69CBCB1GEThello1A61B78A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - hellofunctionDB70DA8B
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:043309344022:"
            - Ref: HelloApi3F989F66
            - /test-invoke-stage/GET/hello
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/hello/GET/ApiPermission.Test.tslambdastackdevelopHelloApiC69CBCB1.GET..hello
  HelloApihelloGET34B3ECE0:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - hellofunctionDB70DA8B
                  - Arn
              - /invocations
      ResourceId:
        Ref: HelloApihello0292B1E3
      RestApiId:
        Ref: HelloApi3F989F66
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/hello/GET/Resource
  HelloApidocs57AB0EEC:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - HelloApi3F989F66
          - RootResourceId
      PathPart: docs
      RestApiId:
        Ref: HelloApi3F989F66
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/docs/Resource
  HelloApidocsGETApiPermissiontslambdastackdevelopHelloApiC69CBCB1GETdocsC0E48803:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - hellofunctionDB70DA8B
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:043309344022:"
            - Ref: HelloApi3F989F66
            - /
            - Ref: HelloApiDeploymentStagedev13C3ED9E
            - /GET/docs
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/docs/GET/ApiPermission.tslambdastackdevelopHelloApiC69CBCB1.GET..docs
  HelloApidocsGETApiPermissionTesttslambdastackdevelopHelloApiC69CBCB1GETdocs90B1143E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - hellofunctionDB70DA8B
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:043309344022:"
            - Ref: HelloApi3F989F66
            - /test-invoke-stage/GET/docs
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/docs/GET/ApiPermission.Test.tslambdastackdevelopHelloApiC69CBCB1.GET..docs
  HelloApidocsGETFEB011E8:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - hellofunctionDB70DA8B
                  - Arn
              - /invocations
      ResourceId:
        Ref: HelloApidocs57AB0EEC
      RestApiId:
        Ref: HelloApi3F989F66
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/HelloApi/Default/docs/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/12PzU7DMBCEn6V3d2laIc4tCC4FqlTiGm2TbXB+7MhrE0WW3x3ZCVBxmm927bFnC9lDBtkKR16XVbvu5AX82WLZChy58BJ78LnuSDxeVdKT7mQ5RTtTEB32lwrBH3Ei80GGpVZx/98/O1XahU9keslxEwTvCmQmy7CPIngHB1e2ZA/ItKQXSlfUMLwl+U3qdM3gj7p+MdoN6dGFg8BB1mhpxAl8Tmz3g0wlFnyiodNTT8rG6Y07W6xT3RlyYu1MSekzP2YJmvmV7Keu4mimEP7OpUYxSKo6nnh3dnD29noQsRo0fPe13UB2D5tVw1KujVNW9gT5rN9iyLOkqQEAAA==
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/CDKMetadata/Default
Outputs:
  HelloApiEndpoint91438085:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: HelloApi3F989F66
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: HelloApiDeploymentStagedev13C3ED9E
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
